import type { Metadata } from "next";
import { Fira_Code, Geist, Geist_Mono, Playwrite_NZ_Guides } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/ui/navigation/Navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playWriteNewZealandBasicGuides = Playwrite_NZ_Guides({
  variable: "--font-playwrite-nz-guides",
  weight: ["400"],
});

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  weight: ['300', '400', '500', '600', '700']
})

const clashDisplay = localFont({
  src: "./public/fonts/ClashDisplay/ClashDisplay-Bold.woff2",
  variable: "--font-clash-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${clashDisplay.variable} ${firaCode.variable} ${geistMono.variable} ${playWriteNewZealandBasicGuides.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
